/*meses=['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre'
, 'octubre', 'noviembre', 'diciembre',80]

console.log( meses.length ); */ 
//-------------------------------------------
/*var n1=6
var n2=7

r=++n1+n2

console.log(r)*/
//-------------------------------------------
//par o impar

/*let num=665
let div=2
res=num%2

if(res===0){

console.log('el numero'+'  '+num+'  '+' es par')
} else{

    console.log('el numero'+num+'  '+' es impar')
}*/

/*var num=0

if (num<0){
    console.log('el numero'+ ' '+ num + ' '+  'es negativo')
}else{

    console.log('el numero'+ ' '+ num + ' '+  'es positivo')
}*/


/*let num1=6
let num2=0
let resultado= num1/num2

if(num2==0){
    console.log('error, no se puede dividir en 0 operacion terminada')
}else{
    console.log('el resultado es'+' '+ resultado)
}*/


/*let inslet='a'
let let1='A'
let let2='B'
let let3='C'
let let4='D'


if(inslet=='A'||inslet=='a'){
    console.log('USTED ACERTO')
}else{
    console.log('F DALE PA FUERA MI LOCO')
}*/

/*let n1=8

let n2=5

diferencia= n1-n2

if (n1>n2){
    console.log('El numero'+' '+n1+ ' '+ 'es mayor que el numero'+ ' '+n2+' '+'con una diferencia de '+' '+diferencia)
}else{

    console.log('El numero'+' '+n2+ ' '+ 'es mayor que el numero'+ ' '+n1+' '+'con una diferencia de '+' '+diferencia)
}*/


/*let articulo='comida'
if ( articulo === "vino" || articulo === "cerveza"){
            
console.log('si su eleccion fue '+articulo+' '+'vaya a la barra');
       
       
       }else{
      console.log("vaya a la tienda");
       
       
       }*/

/*let vehiculo='tren'
       if ( vehiculo === "tren" || vehiculo=== "autobus"){


console.log('si su eleccion fue'+' '+vehiculo+' '+'lleve dinero para los pasajes')

       }else if(vehiculo === "carro" || vehiculo=== "bicicleta"){
        console.log('si su eleccion fue'+' '+vehiculo+' '+'no lleve dinero para los pasajes')
       }*/


    /*   var tiempo = 4


var tramo = 200


var velocidad = tramo/tiempo;


if (velocidad >= 40 && velocidad <= 60){    


      console.log('la Velocidad fue de '+ velocidad+' '+ 'Kilometros, has pasado la prueba');


}else{


    console.log('la Velocidad fue de '+ velocidad+' '+ 'Kilometros, has sido descalificado');


     }*/


/*let cantidad_artiulos=20
let valor= 1
const descuento=0.15

let valor1= cantidad_artiulos*valor


if(valor1>=40){

let valordescuento=valor1*descuento
let valorfinal= valor1-valordescuento

console.log('el valor fnal es de'+ ' '+ valorfinal)
} else{


    console.log('lo sentimos, no hay descuento')


}*/

/*let tri1=6
let tri2=8
let tri3=10
let divisor=3

let sumamedia=tri1+tri2+tri3
let media=sumamedia/divisor

if(media>=7){
    console.log('la media es de'+' '+media+' '+' ussted aprobo')
}else{

    console.log('la media es de'+' '+media+' '+' usted no aprobo')

}*/



/*var precios = [20,30,40,50,'yo soy valor inicial']
var valores = precios;
console.log( valores)  //  [20,30,40,50]
precios[0] = 15;
precios[4] = 33;
precios.push(666)
precios[5] = 16;
console.log( precios)  //  [80,30,40,50]
console.log( valores)  //  [80,30,40,50]
//------------------------------------------



var precios = [20,30,40,50,'yo soy valor inicial']
var valores = structuredClone(precios);
console.log( valores)  //  [20,30,40,50,]
precios[1] = 80;
precios.push(666)
precios[4]=12
console.log( precios)  //  [80,30,40,50,]
console.log(valores)  //  [20,30,40,50,'yo soy valor inicial']*/




//------------------------------


